version: '3.1'

services:
  Postgresql-DB:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=django-RateLimit
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django-password
    
    expose:
      - 5432
    ports:
      - 5432:5432